version: '3.8'

services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: ce_study_db
    environment:
      POSTGRES_USER: ce_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: ce_study_assistant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
